{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c7d0a354-4f36-4182-9e8a-8e29cb185b21",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: CPU random generator seem to be failing, disabling hardware random number generation\n",
      "WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "sys.path.append(\"/home/Documents/GitHub/sf3bot\")\n",
    "from MAMEToolkit.emulator import Emulator\n",
    "from MAMEToolkit.emulator import Address\n",
    "from MAMEToolkit.sf_environment.Actions import Actions\n",
    "from Steps import *\n",
    "import gym\n",
    "from gym import spaces\n",
    "import math\n",
    "import numpy as np\n",
    "from Incremental import *\n",
    "\n",
    "\n",
    "# Combines the data of multiple time steps\n",
    "def add_rewards(old_data, new_data):\n",
    "    for k in old_data.keys():\n",
    "        if \"rewards\" in k:\n",
    "            for player in old_data[k]:\n",
    "                new_data[k][player] += old_data[k][player]\n",
    "    return new_data\n",
    "\n",
    "\n",
    "# Returns the list of memory addresses required to train on Street Fighter\n",
    "def setup_memory_addresses():\n",
    "    return {\n",
    "        \"fighting\": Address('0x02011389', 'u8'),\n",
    "        \"winsP1\": Address('0x02011383', 'u8'),\n",
    "        \"winsP2\": Address('0x02011385', 'u8'),\n",
    "        \"healthP1\": Address('0x02068D0A', 's16'),\n",
    "        \"healthP2\": Address('0x020691A2', 's16')\n",
    "    }\n",
    "\n",
    "\n",
    "# Converts and index (action) into the relevant movement action Enum, depending on the player\n",
    "def index_to_move_action(action):\n",
    "    return {\n",
    "        0: [Actions.P1_LEFT],\n",
    "        1: [Actions.P1_LEFT, Actions.P1_UP],\n",
    "        2: [Actions.P1_UP],\n",
    "        3: [Actions.P1_UP, Actions.P1_RIGHT],\n",
    "        4: [Actions.P1_RIGHT],\n",
    "        5: [Actions.P1_RIGHT, Actions.P1_DOWN],\n",
    "        6: [Actions.P1_DOWN],\n",
    "        7: [Actions.P1_DOWN, Actions.P1_LEFT],\n",
    "        8: []\n",
    "    }[action]\n",
    "\n",
    "\n",
    "# Converts and index (action) into the relevant attack action Enum, depending on the player\n",
    "def index_to_attack_action(action):\n",
    "    return {\n",
    "        0: [Actions.P1_JPUNCH],\n",
    "        1: [Actions.P1_SPUNCH],\n",
    "        2: [Actions.P1_FPUNCH],\n",
    "        3: [Actions.P1_JPUNCH, Actions.P1_SPUNCH],\n",
    "        4: [Actions.P1_SKICK],\n",
    "        5: [Actions.P1_FKICK],\n",
    "        6: [Actions.P1_RKICK],\n",
    "        7: [Actions.P1_SKICK, Actions.P1_FKICK],\n",
    "        8: [Actions.P1_JPUNCH, Actions.P1_SKICK],\n",
    "        9: []\n",
    "    }[action]\n",
    "\n",
    "\n",
    "# The Street Fighter specific interface for training an agent against the game\n",
    "class GameEnvGym(gym.Env):\n",
    "\n",
    "    # env_id - the unique identifier of the emulator environment, used to create fifo pipes\n",
    "    # difficulty - the difficult to be used in story mode gameplay\n",
    "    # frame_ratio, frames_per_step - see Emulator class\n",
    "    # render, throttle, debug - see Console class\n",
    "    def __init__(self, env_id, roms_path, difficulty=3, frame_ratio=1, frames_per_step=1, render=True, throttle=False, frame_skip=0, sound=False, debug=False, binary_path=None):\n",
    "        super(GameEnvGym, self).__init__()\n",
    "        \n",
    "        self.difficulty = difficulty\n",
    "        self.frame_ratio = frame_ratio\n",
    "        self.frames_per_step = frames_per_step\n",
    "        self.throttle = throttle\n",
    "        self.emu = Emulator(env_id, roms_path, \"sfiii3n\", setup_memory_addresses(), frame_ratio=frame_ratio, render=render, throttle=throttle, frame_skip=frame_skip, sound=sound, debug=debug, binary_path=binary_path)\n",
    "        self.started = False\n",
    "        self.expected_health = {\"P1\": 0, \"P2\": 0}\n",
    "        self.expected_wins = {\"P1\": 0, \"P2\": 0}\n",
    "        self.round_done = False\n",
    "        self.stage_done = False\n",
    "        self.game_done = False\n",
    "        self.stage = 1\n",
    "        \n",
    "        self.action_space = Incremental(0, 90, 90)\n",
    "        # self.action_space = spaces.Box(low=0, high=90, shape=(4,), dtype=np.uint8)\n",
    "        self.observation_space = spaces.Box(low=0, high=255, shape=(256, 256, 3, 1), dtype=np.uint8)\n",
    "        \n",
    "\n",
    "    # Runs a set of action steps over a series of time steps\n",
    "    # Used for transitioning the emulator through non-learnable gameplay, aka. title screens, character selects\n",
    "    def run_steps(self, steps):\n",
    "        for step in steps:\n",
    "            for i in range(step[\"wait\"]):\n",
    "                self.emu.step([])\n",
    "            self.emu.step([action.value for action in step[\"actions\"]])\n",
    "\n",
    "    # Must be called first after creating this class\n",
    "    # Sends actions to the game until the learnable gameplay starts\n",
    "    # Returns the first few frames of gameplay\n",
    "    def start(self):\n",
    "        if self.throttle:\n",
    "            for i in range(int(250/self.frame_ratio)):\n",
    "                self.emu.step([])\n",
    "        self.run_steps(set_difficulty(self.frame_ratio, self.difficulty))\n",
    "        self.run_steps(start_game(self.frame_ratio))\n",
    "        frames = self.wait_for_fight_start()\n",
    "        self.started = True\n",
    "        return frames\n",
    "\n",
    "    # Observes the game and waits for the fight to start\n",
    "    def wait_for_fight_start(self):\n",
    "        data = self.emu.step([])\n",
    "        while data[\"fighting\"] == 0:\n",
    "            data = self.emu.step([])\n",
    "        self.expected_health = {\"P1\": data[\"healthP1\"], \"P2\": data[\"healthP2\"]}\n",
    "        data = self.gather_frames([])\n",
    "        return data[\"frame\"]\n",
    "\n",
    "    def reset(self):\n",
    "        if self.game_done:\n",
    "            return self.new_game()\n",
    "        elif self.stage_done:\n",
    "            return self.next_stage()\n",
    "        elif self.round_done:\n",
    "            return self.next_round()\n",
    "        else:\n",
    "            raise EnvironmentError(\"Reset called while gameplay still running\")\n",
    "\n",
    "    # To be called when a round finishes\n",
    "    # Performs the necessary steps to take the agent to the next round of gameplay\n",
    "    def next_round(self):\n",
    "        self.round_done = False\n",
    "        self.expected_health = {\"P1\": 0, \"P2\": 0}\n",
    "        return self.wait_for_fight_start()\n",
    "\n",
    "    # To be called when a game finishes\n",
    "    # Performs the necessary steps to take the agent(s) to the next game and resets the necessary book keeping variables\n",
    "    def next_stage(self):\n",
    "        self.wait_for_continue()\n",
    "        self.run_steps(next_stage(self.frame_ratio))\n",
    "        self.expected_health = {\"P1\": 0, \"P2\": 0}\n",
    "        self.expected_wins = {\"P1\": 0, \"P2\": 0}\n",
    "        self.round_done = False\n",
    "        self.stage_done = False\n",
    "        return self.wait_for_fight_start()\n",
    "\n",
    "    def new_game(self):\n",
    "        self.wait_for_continue()\n",
    "        self.run_steps(new_game(self.frame_ratio))\n",
    "        self.expected_health = {\"P1\": 0, \"P2\": 0}\n",
    "        self.expected_wins = {\"P1\": 0, \"P2\": 0}\n",
    "        self.round_done = False\n",
    "        self.stage_done = False\n",
    "        self.game_done = False\n",
    "        self.stage = 1\n",
    "        return self.wait_for_fight_start()\n",
    "\n",
    "    # Steps the emulator along until the screen goes black at the very end of a game\n",
    "    def wait_for_continue(self):\n",
    "        data = self.emu.step([])\n",
    "        if self.frames_per_step == 1:\n",
    "            while data[\"frame\"].sum() != 0:\n",
    "                data = self.emu.step([])\n",
    "        else:\n",
    "            while data[\"frame\"][0].sum() != 0:\n",
    "                data = self.emu.step([])\n",
    "\n",
    "    # Steps the emulator along until the round is definitely over\n",
    "    def run_till_victor(self, data):\n",
    "        while self.expected_wins[\"P1\"] == data[\"winsP1\"] and self.expected_wins[\"P2\"] == data[\"winsP2\"]:\n",
    "            data = add_rewards(data, self.sub_step([]))\n",
    "        self.expected_wins = {\"P1\":data[\"winsP1\"], \"P2\":data[\"winsP2\"]}\n",
    "        return data\n",
    "\n",
    "    # Checks whether the round or game has finished\n",
    "    def check_done(self, data):\n",
    "        if data[\"fighting\"] == 0:\n",
    "            data = self.run_till_victor(data)\n",
    "            self.round_done = True\n",
    "            if data[\"winsP1\"] == 2:\n",
    "                self.stage_done = True\n",
    "                self.stage += 1\n",
    "            if data[\"winsP2\"] == 2:\n",
    "                self.game_done = True\n",
    "        return data\n",
    "\n",
    "    # Collects the specified amount of frames the agent requires before choosing an action\n",
    "    def gather_frames(self, actions):\n",
    "        data = self.sub_step(actions)\n",
    "        frames = [data[\"frame\"]]\n",
    "        for i in range(self.frames_per_step - 1):\n",
    "            data = add_rewards(data, self.sub_step(actions))\n",
    "            frames.append(data[\"frame\"])\n",
    "        data[\"frame\"] = frames[0] if self.frames_per_step == 1 else frames\n",
    "        return data\n",
    "\n",
    "    # Steps the emulator along by one time step and feeds in any actions that require pressing\n",
    "    # Takes the data returned from the step and updates book keeping variables\n",
    "    def sub_step(self, actions):\n",
    "        data = self.emu.step([action.value for action in actions])\n",
    "\n",
    "        p1_diff = (self.expected_health[\"P1\"] - data[\"healthP1\"])\n",
    "        p2_diff = (self.expected_health[\"P2\"] - data[\"healthP2\"])\n",
    "        self.expected_health = {\"P1\": data[\"healthP1\"], \"P2\": data[\"healthP2\"]}\n",
    "\n",
    "        rewards = p2_diff - p1_diff\n",
    "        \n",
    "        # rewards = {\n",
    "        #     \"P1\": (p2_diff-p1_diff),\n",
    "        #     \"P2\": (p1_diff-p2_diff)\n",
    "        # }\n",
    "\n",
    "        data[\"rewards\"] = rewards\n",
    "        return data\n",
    "\n",
    "    # Steps the emulator along by the requested amount of frames required for the agent to provide actions\n",
    "    def step(self, action):\n",
    "        if self.started:\n",
    "            if not self.round_done and not self.stage_done and not self.game_done:\n",
    "                actions = []\n",
    "                print(action)\n",
    "                actions += index_to_move_action(action//10)\n",
    "                actions += index_to_attack_action(action % 10)\n",
    "                data = self.gather_frames(actions)\n",
    "                data = self.check_done(data)\n",
    "                return data[\"frame\"], data[\"rewards\"], self.round_done, self.stage_done, self.game_done\n",
    "            else:\n",
    "                raise EnvironmentError(\"Attempted to step while characters are not fighting\")\n",
    "        else:\n",
    "            raise EnvironmentError(\"Start must be called before stepping\")\n",
    "\n",
    "    # Safely closes emulator\n",
    "    def close(self):\n",
    "        self.emu.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "501511e1-5979-498c-a939-4a8bea9d9fe9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: CPU random generator seem to be failing, disable hardware random number generation\n",
      "WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 84: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 84: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 93: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 93: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 102: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 102: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 68: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 68: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 79: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 79: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 79: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 88: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 66: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 66: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 66: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 75: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 75: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/fonts.conf\", line 82: unknown element \"blank\"\n"
     ]
    },
    {
     "ename": "BrokenPipeError",
     "evalue": "[Errno 32] Broken pipe",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mBrokenPipeError\u001b[0m                           Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_41924/1547926004.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mroms_path\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"./roms/\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m \u001b[0menv\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mGameEnvGym\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"env1\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mroms_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m \u001b[0menv\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstart\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;32mwhile\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/tmp/ipykernel_41924/2510275692.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, env_id, roms_path, difficulty, frame_ratio, frames_per_step, render, throttle, frame_skip, sound, debug, binary_path)\u001b[0m\n\u001b[1;32m     77\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mframes_per_step\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mframes_per_step\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     78\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mthrottle\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mthrottle\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 79\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0memu\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mEmulator\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0menv_id\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mroms_path\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"sfiii3n\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msetup_memory_addresses\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mframe_ratio\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mframe_ratio\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrender\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrender\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mthrottle\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mthrottle\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mframe_skip\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mframe_skip\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msound\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0msound\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdebug\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdebug\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbinary_path\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mbinary_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     80\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstarted\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mFalse\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     81\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexpected_health\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m\"P1\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"P2\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/Emulator.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, env_id, roms_path, game_id, memory_addresses, frame_ratio, render, throttle, frame_skip, sound, debug, binary_path)\u001b[0m\n\u001b[1;32m     53\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconsole\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mConsole\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mroms_path\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mgame_id\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrender\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrender\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mthrottle\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mthrottle\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mframe_skip\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mframe_skip\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msound\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0msound\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdebug\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdebug\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbinary_path\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mbinary_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     54\u001b[0m         \u001b[0matexit\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mregister\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclose\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 55\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_for_resource_registration\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     56\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcreate_lua_variables\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     57\u001b[0m         \u001b[0mbitmap_format\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_bitmap_format\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/Emulator.py\u001b[0m in \u001b[0;36mwait_for_resource_registration\u001b[0;34m(self, max_attempts)\u001b[0m\n\u001b[1;32m    101\u001b[0m                 \u001b[0mscreen_registered\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;34m\"nil\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    102\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mprogram_registered\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 103\u001b[0;31m                 \u001b[0mresult\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconsole\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwriteln\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'print(manager:machine().devices[\":maincpu\"].spaces[\"program\"])'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexpect_output\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mraiseError\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    104\u001b[0m                 \u001b[0mprogram_registered\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;34m\"nil\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    105\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mattempt\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mmax_attempts\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/Console.py\u001b[0m in \u001b[0;36mwriteln\u001b[0;34m(self, command, expect_output, timeout, raiseError)\u001b[0m\n\u001b[1;32m     78\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mwriteln\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcommand\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexpect_output\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0.5\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mraiseError\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     79\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprocess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstdin\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwrite\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcommand\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mencode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"utf-8\"\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34mb'\\n'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 80\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprocess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstdin\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mflush\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     81\u001b[0m         \u001b[0moutput\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreadAll\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     82\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mBrokenPipeError\u001b[0m: [Errno 32] Broken pipe"
     ]
    }
   ],
   "source": [
    "import random\n",
    "\n",
    "roms_path = \"./roms/\"\n",
    "env = GameEnvGym(\"env1\", roms_path)\n",
    "env.start()\n",
    "while True:\n",
    "    move_action = random.randint(0, 8)\n",
    "    attack_action = random.randint(0, 9)\n",
    "    frames, reward, round_done, stage_done, game_done = env.step(move_action, attack_action)\n",
    "    if game_done or stage_done or round_done:\n",
    "        env.reset()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "5302cf35-4a52-4257-8688-f3a2bd50917b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: CPU random generator seem to be failing, disable hardware random number generation\n",
      "WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 84: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 84: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 93: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 93: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 102: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/30-metric-aliases.conf\", line 102: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 33: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 59: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 68: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 68: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 79: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 79: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 79: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/40-nonlatin.conf\", line 88: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 23: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 39: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 56: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 66: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 66: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 66: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 75: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/conf.d/45-latin.conf\", line 75: Having multiple <family> in <alias> isn't supported and may not work as expected\n",
      "Fontconfig warning: \"/home/a/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/mame/fonts/fonts.conf\", line 82: unknown element \"blank\"\n"
     ]
    },
    {
     "ename": "BrokenPipeError",
     "evalue": "[Errno 32] Broken pipe",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mBrokenPipeError\u001b[0m                           Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_41924/3345942748.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mPPO\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mPPO\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mroms_path\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"./roms/\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0menv\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mGameEnvGym\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"env1\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mroms_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0menv\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstart\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mmodel\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mPPO\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0menv\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/tmp/ipykernel_41924/2510275692.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, env_id, roms_path, difficulty, frame_ratio, frames_per_step, render, throttle, frame_skip, sound, debug, binary_path)\u001b[0m\n\u001b[1;32m     77\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mframes_per_step\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mframes_per_step\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     78\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mthrottle\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mthrottle\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 79\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0memu\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mEmulator\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0menv_id\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mroms_path\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"sfiii3n\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msetup_memory_addresses\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mframe_ratio\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mframe_ratio\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrender\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrender\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mthrottle\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mthrottle\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mframe_skip\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mframe_skip\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msound\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0msound\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdebug\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdebug\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbinary_path\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mbinary_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     80\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstarted\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mFalse\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     81\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexpected_health\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m\"P1\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"P2\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/Emulator.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, env_id, roms_path, game_id, memory_addresses, frame_ratio, render, throttle, frame_skip, sound, debug, binary_path)\u001b[0m\n\u001b[1;32m     53\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconsole\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mConsole\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mroms_path\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mgame_id\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrender\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrender\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mthrottle\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mthrottle\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mframe_skip\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mframe_skip\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msound\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0msound\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdebug\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdebug\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbinary_path\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mbinary_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     54\u001b[0m         \u001b[0matexit\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mregister\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclose\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 55\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_for_resource_registration\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     56\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcreate_lua_variables\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     57\u001b[0m         \u001b[0mbitmap_format\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_bitmap_format\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/Emulator.py\u001b[0m in \u001b[0;36mwait_for_resource_registration\u001b[0;34m(self, max_attempts)\u001b[0m\n\u001b[1;32m    101\u001b[0m                 \u001b[0mscreen_registered\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;34m\"nil\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    102\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mprogram_registered\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 103\u001b[0;31m                 \u001b[0mresult\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconsole\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwriteln\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'print(manager:machine().devices[\":maincpu\"].spaces[\"program\"])'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexpect_output\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mraiseError\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    104\u001b[0m                 \u001b[0mprogram_registered\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;34m\"nil\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    105\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mattempt\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mmax_attempts\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.9/site-packages/MAMEToolkit/emulator/Console.py\u001b[0m in \u001b[0;36mwriteln\u001b[0;34m(self, command, expect_output, timeout, raiseError)\u001b[0m\n\u001b[1;32m     78\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mwriteln\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcommand\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexpect_output\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0.5\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mraiseError\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     79\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprocess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstdin\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwrite\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcommand\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mencode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"utf-8\"\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34mb'\\n'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 80\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprocess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstdin\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mflush\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     81\u001b[0m         \u001b[0moutput\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreadAll\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     82\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mBrokenPipeError\u001b[0m: [Errno 32] Broken pipe"
     ]
    }
   ],
   "source": [
    "from PPO import PPO\n",
    "roms_path = \"./roms/\"\n",
    "env = GameEnvGym(\"env1\", roms_path)\n",
    "env.start()\n",
    "model = PPO(env)\n",
    "model.learn(100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4796cb3b-37b3-4c51-b778-e887754cb6d8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
